version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: payment-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - payment-network

  payment-api:
    build:
      context: .
      dockerfile: Payment.Api/Dockerfile
    container_name: payment-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Redis__ConnectionString=redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - payment-network

volumes:
  redis-data:
    driver: local

networks:
  payment-network:
    driver: bridge
